# Generated by Django 3.1.1 on 2024-04-30 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20240428_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
    ]
