# Generated by Django 3.1.1 on 2024-04-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_remove_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='dest_location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastlocation', to='maps.location'),
        ),
        migrations.AlterField(
            model_name='map',
            name='starting_location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstlocation', to='maps.location'),
        ),
    ]
