# Generated by Django 3.1.1 on 2024-04-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20240430_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
    ]
